[general]
import = ["~/.config/alacritty/alacritty-theme/themes/tokyo_night_enhanced.toml"]

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 15

[window]
opacity = 0.8
decorations = "buttonless"

[colors]
transparent_background_colors = true

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
  # for tmux 
  { key = "B", mods = "Command", chars = "\x1f" }
]
