import=["~/.config/alacritty/themes/themes/solarized-dark-high-contrast.toml"]
[font]
normal={family="Hack Nerd Font Mono",style="Regular"}
size=15

[keyboard]

[window]
opacity=0.8
decorations="None"

[colors]
transparent_background_colors = true
