import = ["~/.config/alacritty/alacritty-theme/themes/nightfox.toml"]
[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 15

[keyboard]

[window]
opacity = 0.8
decorations = "buttonless"

[colors]
transparent_background_colors = true

[mouse]
hide_when_typing = false
