#tmux new to create new session
#tmux dettach to detach session ctrl b d
#tmux attach to attach to running session
#tmux ls to check sessions
#tmux choose-tree -s ctrl b s
#tmux switch-client ctrl b L
#tmux new-ww ctrl b c
#tmux next ctrl b n
#tmux prev ctrl b p
#tmux list-window ctrl b w
#tmux split-w ctrl b "
#tmux split-w -h ctrl %
#tmux selectp -t :.+ ctrl b o cycle to prev pane
#tmux resize-pane -Z ctrl b z

set -g default-terminal "screen-256color"
#
# # maximize pane
# bind -r m resize-pane -Z
set -g mouse on
set -g focus-events on
set -g prefix C-_
unbind C-b
